#!/bin/bash

# Delete the VPC along with its associated resources
echo "Deleting VPC and associated resources..." 

if [ -z "$1" ]; then
  echo "Argument missing: VPC_ID"
else
    export VPC_ID=$1
fi

if [ -z "$2" ]; then
  echo "Argument missing: IGW_ID"
else
    export IGW_ID=$2
fi

if [ -z "$3" ]; then
  echo "Argument missing: SUBNET_ID"
else
    export SUBNET_ID=$3
fi


if [ -z "$4" ]; then
  echo "Argument missing: RT_ID"
else
    export RT_ID=$4
fi


# Detach and delete the IGW
aws ec2 detach-internet-gateway \
--internet-gateway-id $IGW_ID \
--vpc-id $VPC_ID \

AS_ID=$(
aws ec2 describe-route-tables \
--filters "Name=vpc-id,Values=$VPC_ID" "Name=association.subnet-id,Values=$SUBNET_ID" \
--query "RouteTables[0].Associations[0].RouteTableAssociationId" \
--output text
)

aws ec2 disassociate-route-table \
--association-id $AS_ID 

# Delete all subnets in the VPC
aws ec2 delete-subnet \
--subnet-id $SUBNET_ID 

# Delete the VPC
aws ec2 delete-vpc --vpc-id $VPC_ID --region us-east-1