#!/bin/bash
echo "Deploying S3 bucket via CFN..."
set -e

STACK_NAME="cfn-s3-simple"
aws cloudformation deploy \
--template-file template.yaml \
--no-execute-changeset \
--region us-west-1 \
--stack-name $STACK_NAME 